env:
  global:
  - DIST_REPO="dist"
  - PKG_RELEASE=f5-adcaas-openstack-$(git describe --tags --abbrev=0).tar.gz

script:
- scripts/build_dist.sh
- tar cvzf ${PKG_RELEASE} dist
- cp ${PKG_RELEASE} dist/
deploy:
  - provider: releases
    api_key:
      secure: "$GITHUB_TOKEN"
    file:
      - abcd.tar.gz
    skip_cleanup: true
    overwrite: true
    on:
      repo: JingL1/f5-adcaas-openstack
      tags: true
