env:
  global:
  - PKG_RELEASE="f5-adcaas-openstack-0.0.0.tar.gz"
 
   
script:
- scripts/build_dist.sh
- tar cvzf ${PKG_RELEASE} dist
- cp ${PKG_RELEASE} dist/
deploy:
  - provider: releases
    api_key:
      secure: "$GITHUB_TOKEN"
    file:
      - ${PKG_RELEASE}
    skip_cleanup: true
    overwrite: true
    on:
      repo: JingL1/f5-adcaas-openstack
#       tags: true
