# TODO-1:integrating function below into the stage of "publish-image-and-docs"
env:
  global:
  - PKG_RELEASE="f5-adcaas-openstack-$(git describe --tags --abbrev=0).tar.gz"   
script:
- scripts/build_dist.sh
- tar cvzf ${PKG_RELEASE} dist
- cp ${PKG_RELEASE} dist/

# Release a new version in github
deploy:
  - provider: releases
# TODO-2: my token are going to be removed, using zhaoqin's token instead
    api_key:
      secure: "$GITHUB_TOKEN"
    file:
      - ${PKG_RELEASE}
    skip_cleanup: true
    overwrite: true
 # TODO-3: repo updates to F5Networks/f5-adcaas-openstack
    on:
      repo: JingL1/f5-adcaas-openstack
      tags: true
