env:
  global:
  - DIST_REPO="dist"

script:
- scripts/build_dist.sh
- tar cvzf abcd.tar.gz dist
- cp abcd.tar.gz dist/
deploy:
  - provider: releases
    api_key:
      secure: "$GITHUB_TOKEN"
    file:
      - abcd.tar.gz
    skip_cleanup: true
    overwrite: true
    on:
      repo: JingL1/f5-adcaas-openstack
      tags: true
